gan_config:
  dp: false
  dataset: 
    name: gaussians_grid
    params:
      sigma: &sigma 0.05
      n_modes: 25
      sample_size: 25600
  train_transform:
    Normalize:
      mean: &mean [0., 0.]
      std: &std [1.415, 1.415]
  prior: normal
  eval: true
  generator:
    name: MLPGenerator
    params:
      mean: *mean
      std: *std
      z_dim: 2
      n_layers: 3
      n_hid: 128
      n_out: 2
    ckpt_path: checkpoints/mlp/G_25_gauss_wass.pth
  discriminator:
    name: MLPDiscriminator
    params:
      mean: *mean
      std: *std
      n_layers: 3
      n_hid: 256
      n_in: 2
    ckpt_path: checkpoints/mlp/D_25_gauss_wass.pth
  fake_score: 1.120748509168625
  real_score: &real_score 1.3069784998893739
  mean_score: 1.2138635045289994


train_batch_size: 256
n_epochs: &n_epochs 500
criterion_g: &criterion_g
  name: Wasserstein1Loss
criterion_d: &criterion_d
  name: Wasserstein1Loss
optimizer_g: &optimizer_g
  name: Adam
  params:
    lr: 0.0001
    betas: [0.5, 0.99]
optimizer_d: &optimizer_d
  name: Adam
  params:
    lr: 0.0001
    betas: [0.5, 0.99]
trainer_kwargs: &trainer_kwargs
  n_dis: 1 #10
  gp_coef: 0.7
  sample_size: 5000
  grad_acc_steps: 1
  sample_steps: &sample_steps 5

range: &range [-2.5, 2.5]
