gan_config:
  dp: false
  dataset: 
    name: gaussians_ring
    params:
      sigma: &sigma 0.02 # 0.05
      n_modes: 8
      rad: 2.0
      sample_size: 50000
      weights: [4.0, 1, 2.0, 1, 0.5, 1, 0.25, 1] # [1.66, 1, 1, 1.33, 1, 1, 0.66, 1]
  train_transform:
    Normalize:
      mean: &mean [0., 0.]
      std: &std [1., 1.]
  prior: normal
  eval: true
  generator:
    name: MLPGenerator
    params:
      mean: *mean
      std: *std
      z_dim: 256 # 256
      n_layers: 2
      n_hid: 128
      n_out: 2
    ckpt_path: log/dumb_feature_PriorTarget_train/mlp_ring_0.1_46/checkpoints/g_500.pth #checkpoints/mlp/G_8_gauss.pth
  discriminator:
    name: MLPDiscriminator
    params:
      mean: *mean
      std: *std
      n_layers: 2
      n_hid: 128
      n_in: 2
    ckpt_path: log/dumb_feature_PriorTarget_train/mlp_ring_0.1_46/checkpoints/d_500.pth #checkpoints/mlp/D_8_gauss.pth
  fake_score: -1.7566776394844055
  real_score: &real_score 8.224320197105408
  mean_score: 3.233821278810501


train_batch_size: 256
# n_epochs: &n_epochs 500
n_train_iters: &n_train_iters 75000
criterion_g: &criterion_g
  name: JensenNSLoss
criterion_d: &criterion_d
  name: JensenNSLoss
optimizer_g: &optimizer_g
  name: Adam
  params:
    lr: 0.0001
    betas: [0.5, 0.999]
optimizer_d: &optimizer_d
  name: Adam
  params:
    lr: 0.0001
    betas: [0.5, 0.999]
trainer_kwargs: &trainer_kwargs
  n_dis: 1 #3
  sample_size: 2500 #0
  grad_acc_steps: 1
  sample_steps: &sample_steps 1
  r1_coef: 0.05
  step_every: 1000000

range: &range [-2.5, 2.5]

