# sample
sample_params: 
    feature: *feature
    distribution: *target_distribution

    params:
      n_steps: *sample_steps #25
      weight_step: *weight_step
      step_size: *step_size
      n_sampling_steps: 1
      verbose: false
      save_every: 1
      weight_upd_every: 5
      feature_reset_every: 1
      sweet_init: *sweet_init
      
# train
train_params:
  n_epochs: *n_epochs
  optimizer_g: *optimizer_g
  optimizer_d: *optimizer_d
  criterion_g: *criterion_g
  criterion_d: *criterion_g
  device: *device
  save_dir: *dir
  sub_dir: *sub_dir
  trainer_kwargs: 
    <<: *trainer_kwargs
    importance_sampling: false
    # sample_steps: *sample_steps


# afterall
afterall_params:
    results_dir: *dir
    sub_dir: *sub_dir
    init_wandb: false #true
    
    remove_chains: false #true


callbacks:
  train_callbacks: &train_callbacks
    log_callback:
      name: TrainLogCallback
      params:
        invoke_every: 10
    plot2d:
      name: Plot2dCallback
      params:
        modes: true
        invoke_every: 10
        every: 1
        save_dir: null
        range: *range
    plot2d_dis:
      name: Plot2dEnergyCallback
      params:
        gan: true
        invoke_every: 10
        every: 1
        save_dir: null
    emd:
      name: EMDCallback
      params:
        np_dataset: true
        invoke_every: 100
        update_input: true 
    hqr_js:
      name: HQRCallback
      params:
        np_dataset: true
        modes: true
        sigma: *sigma
        invoke_every: *n_epochs
        update_input: true  
    log_emd:
      name: LogCallback
      params:
        invoke_every: 100
        keys:
          - EMD
        save_dir: null
    log_hqr:
      name: LogCallback
      params:
        invoke_every: *n_epochs
        keys:
          - HQR
        save_dir: null
    log_jsd:
      name: LogCallback
      params:
        invoke_every: *n_epochs
        keys:
          - JSD
        save_dir: null
    ckpt:
      name: CheckpointCallback
      params:
        gan: true
        invoke_every: *n_epochs
        save_dir: null

  feature_callbacks: &feature_callbacks {}
