# seed: 42

# sample
sample_params: &sample_params
    feature: *feature
    distribution: *target_distribution

    params:
      n_steps: *sample_steps
      weight_step: *weight_step
      n_sampling_steps: 1
      verbose: false
      save_every: 1
      collect_imgs: false
      sampling: *sampling
      mcmc_args:
        <<: *mcmc_args
        step_size: *step_size
      keep_graph: true
      
# train
train_params: &train_params
  n_train_iters: *n_train_iters
  optimizer_g: *optimizer_g
  optimizer_d: *optimizer_d
  criterion_g: *criterion_g
  criterion_d: *criterion_g
  device: *device
  save_dir: *dir
  sub_dir: *sub_dir
  trainer_kwargs: 
    <<: *trainer_kwargs
    eval_every: 2500
    replay_prob: 0.95
    replay_size: 50000
    meta_rate: 0.5


# afterall
afterall_params:
    results_dir: *dir
    sub_dir: *sub_dir
    init_wandb: false
    remove_chains: true

wandb_init_params: &wandb_init_params
  project: &wandb_project maxent_gan
  entity: &wandb_account sverdoot
  name: *name
  group: train
  config:
    sample_params:
      <<: *sample_params
    train_params:
      <<: *train_params

callbacks:
  train_callbacks: &train_callbacks
    log_callback:
      name: TrainLogCallback
      params:
        invoke_every: 500
    fid_callback:
      name: FIDCallback
      params:
        data_stat_path: stats/cifar10/fid_stats_cifar10.npz
        invoke_every: 2500
        dp: true
        batch_size: 256
    is_callback:
      name: InceptionScoreCallback
      params:
        invoke_every: 2500
        dp: true
        batch_size: 256
    img_callback:
      name: PlotImagesCallback
      params:
        invoke_every: 2500
    log_fid:
      name: LogCallback
      params:
        invoke_every: 2500
        keys:
          - fid
        save_dir: null
    log_is:
      name: LogCallback
      params:
        invoke_every: 2500
        keys:
          - inception_score
        save_dir: null
    log_imgs:
      name: LogCallback
      params:
        invoke_every: 2500
        keys:
          - grid
        save_dir: null
    log_weight:
      name: LogCallback
      params:
        invoke_every: 2500
        keys:
          - weight_norm
        save_dir: null
    ckpt:
      name: CheckpointCallback
      params:
        gan: true
        invoke_every: 50000
        save_dir: null
    wandb_loss:
      name: WandbCallback
      params:
        init_params:
          <<: *wandb_init_params
          reinit: False
        invoke_every: 10
        keys:
          - loss_d
          - loss_g
          - grad_norm_d
          - grad_norm_g
    wandb_metrics:
      name: WandbCallback
      params:
        init_params:
          <<: *wandb_init_params
          reinit: False
        invoke_every: 2500
        keys:
          - fid
          - inception_score
    wandb_imgs:
      name: WandbCallback
      params:
        init_params:
          <<: *wandb_init_params
          reinit: False
        invoke_every: 2500
        keys:
          - imgs


  feature_callbacks: &feature_callbacks {}
