dir: &dir log/cluster_feature
n_steps: &n_steps 1000 #0
every: &every 50
seed: null
sweet_init: &sweet_init false

device: &device 'cuda'
total_n: &total_n 10000 #
batch_size: &batch_size 5000


data_batch_size: *batch_size
weight_step: &weight_step 1 #0.01
step_size: &step_size 0.1
name: &name mlp_cluster
burn_in_steps: &burn_in_steps 0. #500.
start_sample: &start_sample 0.
sub_dir: &sub_dir mlp
version: &version '0'
kernel: &kernel GaussianKernel
suffix: *step_size
dis_emb: &dis_emb False