dir: &dir log/dumb_feature
n_steps: &n_steps 1000 #2000
every: &every 20 #50
seed: null
sweet_init: &sweet_init false

device: &device 'cuda'
burn_in_steps: &burn_in_steps 0.0
start_sample: &start_sample 0.0
total_n: &total_n 8200
batch_size: &batch_size 180
data_batch_size: *batch_size
weight_step: &weight_step 0.1
step_size: &step_size 0.01
name: &name mmc_dcgan_dumb
sub_dir: &sub_dir mmc_dcgan
suffix: *step_size
